#ifndef CONSTANTS_ITEMS_Z_CRYSTAL_H
#define CONSTANTS_ITEMS_Z_CRYSTAL_H

#include "../../config.h"

#define ITEM_Z_CRYSTAL_START (NORMALIUM_Z)
#define ITEM_NORMALIUM_Z       (ITEM_Z_CRYSTAL_START + 0)
#define ITEM_FIGHTINIUM_Z      (ITEM_Z_CRYSTAL_START + 1)
#define ITEM_FLYINIUM_Z        (ITEM_Z_CRYSTAL_START + 2)
#define ITEM_POISONIUM_Z       (ITEM_Z_CRYSTAL_START + 3)
#define ITEM_GROUNDIUM_Z       (ITEM_Z_CRYSTAL_START + 4)
#define ITEM_ROCKIUM_Z         (ITEM_Z_CRYSTAL_START + 5)
#define ITEM_BUGIUM_Z          (ITEM_Z_CRYSTAL_START + 6)
#define ITEM_GHOSTIUM_Z        (ITEM_Z_CRYSTAL_START + 7)
#define ITEM_STEELIUM_Z        (ITEM_Z_CRYSTAL_START + 8)
#define ITEM_FIREIUM_Z         (ITEM_Z_CRYSTAL_START + 9)
#define ITEM_WATERIUM_Z        (ITEM_Z_CRYSTAL_START + 10)
#define ITEM_GRASSIUM_Z        (ITEM_Z_CRYSTAL_START + 11)
#define ITEM_ELECTRIUM_Z       (ITEM_Z_CRYSTAL_START + 12)
#define ITEM_PSYCHIUM_Z        (ITEM_Z_CRYSTAL_START + 13)
#define ITEM_ICIUM_Z           (ITEM_Z_CRYSTAL_START + 14)
#define ITEM_DRAGONIUM_Z       (ITEM_Z_CRYSTAL_START + 15)
#define ITEM_DARKINIUM_Z       (ITEM_Z_CRYSTAL_START + 16)
#define ITEM_FAIRIUM_Z         (ITEM_Z_CRYSTAL_START + 17)

#define ITEM_Z_CRYSTAL_END     ITEM_FAIRIUM_Z
#define IS_ITEM_Z_CRYSTAL(item) (item >= ITEM_Z_CRYSTAL_START && item <= ITEM_Z_CRYSTAL_END)
#define NUM_Z_CRYSTALS (ITEM_Z_CRYSTAL_END - ITEM_Z_CRYSTAL_START + 1)

#endif // CONSTANTS_ITEMS_Z_CRYSTAL_H